using System;
using System.Collections.Generic;
using System.Text;

namespace ProjectEuler
{
    public class E2_EvenFibonacciNumbers
    {
        /*
         Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

                By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
         */
        public int SumOfEvenValuedTerms = 2;

        public void Solution()
        {
            int max = 4000000;
            int actual = 3;
            int previous = 2;
            int oldActual;
            
            while (actual<max)
            {
                if (actual % 2 == 0)
                {
                    SumOfEvenValuedTerms += actual;
                }
                oldActual = actual;
                actual += previous;
                previous = oldActual;
            }

            
        }
    }
}
